# Site settings
title: FirmAI
email: d.snow@live.com
description: "Musings of AI in Business"
baseurl: ""
url: "http://firmai.github.io"
twitter_username: 
github_username:  snowde

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
