# Site settings
title: Forthcoming: FirmAI
email: 
description: "Musings of a Computer Scientist."
baseurl: ""
url: "http://firmai.github.io"
twitter_username: karpathy
github_username:  karpathy

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
