# Site settings
title: "Nefy"
email: 
description: "Business and Finance Intelligence"
baseurl: ""
url: "http://nefyweb.github.io"
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
#kramdown:
#  input: GFM
#  auto_ids: true
#  syntax_highlighter: rouge
