# Site settings
title: "Nefy: Business and Finance Intelligence"
email: 
description: "The crossroad of strategy and machine intelligence"
baseurl: ""
url: "http://nefyweb.github.io"
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
